CREATE TABLE app_user (
    username VARCHAR(50) PRIMARY KEY,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(10) NOT NULL CHECK (role IN ('ADMIN', 'CUSTOMER'))
);
CREATE TABLE city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    timezone VARCHAR(60) NOT NULL
);
CREATE TABLE theater (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL REFERENCES city(id),
    name VARCHAR(100) NOT NULL,
    UNIQUE (city_id, name)
);
CREATE TABLE screen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id BIGINT NOT NULL REFERENCES theater(id),
    name VARCHAR(100) NOT NULL,
    UNIQUE (theater_id, name)
);
CREATE TABLE layout_seat (
    screen_id BIGINT NOT NULL REFERENCES screen(id),
    label VARCHAR(10) NOT NULL,
    tier VARCHAR(10) NOT NULL CHECK (tier IN ('REGULAR', 'PREMIUM')),
    PRIMARY KEY (screen_id, label)
);
CREATE TABLE refund_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cutoff_minutes INT NOT NULL CHECK (cutoff_minutes >= 0),
    refund_percent INT NOT NULL CHECK (refund_percent BETWEEN 0 AND 100)
);
CREATE TABLE movie_show (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id BIGINT NOT NULL REFERENCES screen(id),
    title VARCHAR(160) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    regular_price BIGINT NOT NULL CHECK (regular_price > 0),
    premium_price BIGINT NOT NULL CHECK (premium_price > 0),
    weekend_markup INT NOT NULL CHECK (weekend_markup BETWEEN 0 AND 100),
    policy_id BIGINT NOT NULL REFERENCES refund_policy(id),
    status VARCHAR(10) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CANCELLED')),
    CHECK (ends_at > starts_at)
);
CREATE INDEX show_browse ON movie_show(starts_at, screen_id);
CREATE TABLE discount_code (
    code VARCHAR(30) PRIMARY KEY,
    percent INT NOT NULL CHECK (percent BETWEEN 1 AND 100),
    max_discount BIGINT NOT NULL CHECK (max_discount > 0),
    min_spend BIGINT NOT NULL CHECK (min_spend >= 0),
    max_uses INT NOT NULL CHECK (max_uses > 0),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE booking (
    id UUID PRIMARY KEY,
    username VARCHAR(50) NOT NULL REFERENCES app_user(username),
    show_id BIGINT NOT NULL REFERENCES movie_show(id),
    status VARCHAR(12) NOT NULL CHECK (status IN ('HELD', 'CONFIRMED', 'EXPIRED', 'CANCELLED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    subtotal BIGINT NOT NULL CHECK (subtotal >= 0),
    discount BIGINT NOT NULL CHECK (discount >= 0 AND discount <= subtotal),
    total BIGINT NOT NULL CHECK (total = subtotal - discount),
    discount_code VARCHAR(30) REFERENCES discount_code(code),
    refund_cutoff INT NOT NULL,
    refund_percent INT NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (refund_percent BETWEEN 0 AND 100)
);
CREATE INDEX booking_history ON booking(username, created_at);
CREATE INDEX booking_expiry ON booking(status, expires_at);
CREATE TABLE show_seat (
    show_id BIGINT NOT NULL REFERENCES movie_show(id),
    label VARCHAR(10) NOT NULL,
    tier VARCHAR(10) NOT NULL,
    booking_id UUID REFERENCES booking(id),
    PRIMARY KEY (show_id, label)
);
CREATE INDEX seat_booking ON show_seat(booking_id);
CREATE TABLE booking_seat (
    booking_id UUID NOT NULL REFERENCES booking(id),
    label VARCHAR(10) NOT NULL,
    price BIGINT NOT NULL CHECK (price > 0),
    PRIMARY KEY (booking_id, label)
);
CREATE TABLE payment (
    id UUID PRIMARY KEY,
    booking_id UUID NOT NULL REFERENCES booking(id),
    request_key VARCHAR(100) NOT NULL UNIQUE,
    outcome VARCHAR(10) NOT NULL CHECK (outcome IN ('SUCCEEDED', 'DECLINED')),
    amount BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE refund (
    booking_id UUID PRIMARY KEY REFERENCES booking(id),
    amount BIGINT NOT NULL CHECK (amount >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE notification (
    id UUID PRIMARY KEY,
    booking_id UUID NOT NULL REFERENCES booking(id),
    kind VARCHAR(20) NOT NULL,
    message VARCHAR(500) NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    delivered_at TIMESTAMP WITH TIME ZONE,
    attempts INT NOT NULL DEFAULT 0,
    UNIQUE (booking_id, kind)
);
CREATE INDEX notification_due ON notification(delivered_at, due_at);
